export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  ELEVE = 'ROLE_ELEVE',
  DIRECTEUR_ETUDE = 'ROLE_DIRECTEUR_ETUDE',
  PROF_ENCADREUR = 'ROLE_PROF_ENCADREUR',
  ENTREPRISE = 'ROLE_ENTREPRISE',
  INSPECTEUR = 'ROLE_INSPECTEUR',
  DIRECTEUR_ESI = 'ROLE_DIRECTEUR_ESI',
}
